//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class FichaConductor
    {
        public int Id { get; set; }
        public Nullable<int> IdTransportista { get; set; }
        public string Nacionalidad { get; set; }
        public string NacionalidadOtra { get; set; }
        public string EstadoCivil { get; set; }
        public string Rut { get; set; }
        public string DV { get; set; }
        public string Nombre { get; set; }
        public string Paterno { get; set; }
        public string Materno { get; set; }
        public string Sexo { get; set; }
        public string Email { get; set; }
        public string CodTelefono { get; set; }
        public string Telefono { get; set; }
        public string CodTelefono2 { get; set; }
        public string Telefono2 { get; set; }
        public string FechaNacimiento { get; set; }
        public string Direccion { get; set; }
        public string FechaIngreso { get; set; }
        public string FechaHoraCreacion { get; set; }
        public string FechaHoraModificacion { get; set; }
        public string NivelEstudio { get; set; }
        public Nullable<int> IdComuna { get; set; }
        public Nullable<int> Estado { get; set; }
    }
}
