//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Local
    {
        public int Id { get; set; }
        public string Nombre { get; set; }
        public Nullable<int> CodigoInterno { get; set; }
        public Nullable<int> IdFormato { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public Nullable<bool> Activo { get; set; }
        public Nullable<int> MaximoHorasAlertaActiva { get; set; }
        public string NumeroLocal { get; set; }
        public string DescripcionFormato { get; set; }
        public Nullable<bool> FocoAlto { get; set; }
        public Nullable<bool> FocoTablet { get; set; }
        public string RegionLocal { get; set; }
        public Nullable<int> NumeroRegionLocal { get; set; }
        public string ZonaLocal { get; set; }
        public Nullable<int> Etapa { get; set; }
        public string GrupoControl { get; set; }
    
        public virtual Formato Formato { get; set; }
    }
}
