//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Track_Movil
    {
        public string Patente { get; set; }
        public int IdTipoMovil { get; set; }
        public string ProveedorGPS { get; set; }
        public string Transportista { get; set; }
        public string RutTransportista { get; set; }
        public string Opcional { get; set; }
    }
}
