//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Track_TipoAlertas
    {
        public int IdTipoAlerta { get; set; }
        public string NombreTipoAlerta { get; set; }
        public bool AlertaActiva { get; set; }
        public string DescripcionAlerta { get; set; }
        public string Permiso { get; set; }
        public Nullable<decimal> Valor1 { get; set; }
        public Nullable<decimal> Valor2 { get; set; }
        public Nullable<int> Control1 { get; set; }
        public Nullable<int> Control2 { get; set; }
        public Nullable<int> Control3 { get; set; }
        public Nullable<int> Control4 { get; set; }
        public string InfoAlerta { get; set; }
    }
}
