//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Track_Rutas
    {
        public int IdRuta { get; set; }
        public int IdZonaOrigen { get; set; }
        public int IdZonaDestino { get; set; }
        public string ResumenRuta { get; set; }
    }
}
