//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrazaViaje
    {
        public int Id { get; set; }
        public Nullable<int> NroTransporte { get; set; }
        public Nullable<int> Operacion { get; set; }
        public string PatenteTracto { get; set; }
        public string PatenteTrailer { get; set; }
        public string RutTransportista { get; set; }
        public string NombreTransportista { get; set; }
        public string RutConductor { get; set; }
        public string NombreConductor { get; set; }
        public Nullable<int> OrigenCodigo { get; set; }
        public string OrigenDescripcion { get; set; }
        public Nullable<System.DateTime> FHSalidaOrigen { get; set; }
        public Nullable<int> LocalDestino { get; set; }
        public string DestinoDescripcion { get; set; }
        public Nullable<System.DateTime> FHLlegadaDestino { get; set; }
        public Nullable<System.DateTime> FHAperturaPuerta { get; set; }
        public Nullable<System.DateTime> FHSalidaDestino { get; set; }
        public string TipoViaje { get; set; }
        public string ProveedorGPS { get; set; }
        public string DestinoDomicilio { get; set; }
        public string DestinoRegion { get; set; }
        public string DestinoDescripcionRegion { get; set; }
        public string DestinoComuna { get; set; }
        public string DestinoLat { get; set; }
        public string DestinoLon { get; set; }
        public string EstadoViaje { get; set; }
        public Nullable<int> SecuenciaDestino { get; set; }
        public string RamplaProveedorGPS { get; set; }
        public string EstadoPuerta { get; set; }
        public string EstadoLat { get; set; }
        public string EstadoLon { get; set; }
        public string TempSalidaCD { get; set; }
        public Nullable<System.DateTime> FechaHoraCreacion { get; set; }
        public Nullable<System.DateTime> FechaHoraActualizacion { get; set; }
        public Nullable<bool> IngresoSCAT { get; set; }
    }
}
