//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public int Id { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string Rut { get; set; }
        public string DV { get; set; }
        public string Nombre { get; set; }
        public string Paterno { get; set; }
        public string Materno { get; set; }
        public string Email { get; set; }
        public string Telefono { get; set; }
        public Nullable<int> IdDireccion { get; set; }
        public string FechaHoraUltimoAcceso { get; set; }
        public string IpUltimoAcceso { get; set; }
        public string FechaHoraCreacion { get; set; }
        public string FechaHoraModificacion { get; set; }
        public string LoginDias { get; set; }
        public Nullable<bool> Super { get; set; }
        public Nullable<int> Estado { get; set; }
        public Nullable<int> IdPerfil { get; set; }
    }
}
