//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContextLayer.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    using BusinessEntities;
    
    using System.Data.Objects;
    
    public partial class ModelEntities : DbContext
    {
        public ModelEntities()
            : base("name=ModelEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Track_TipoZonas> Track_TipoZonas { get; set; }
        public DbSet<Track_Vertices> Track_Vertices { get; set; }
        public DbSet<Track_Zonas> Track_Zonas { get; set; }
        public DbSet<Track_Movil> Track_Movil { get; set; }
        public DbSet<Track_PuntosRuta> Track_PuntosRuta { get; set; }
        public DbSet<Track_Rutas> Track_Rutas { get; set; }
        public DbSet<Track_RutaOptimaTmp> Track_RutaOptimaTmp { get; set; }
        public DbSet<Track_TipoAlertas> Track_TipoAlertas { get; set; }
        public DbSet<AlertaDefinicion> AlertaDefinicion { get; set; }
        public DbSet<FichaConductor> FichaConductor { get; set; }
        public DbSet<TrazaViaje> TrazaViaje { get; set; }
        public DbSet<Formato> Formato { get; set; }
        public DbSet<Local> Local { get; set; }
        public DbSet<Track_Usuarios> Track_Usuarios { get; set; }
        public DbSet<Track_CodZona_IdZona> Track_CodZona_IdZona { get; set; }
        public DbSet<Configuracion> Configuracion { get; set; }
        public DbSet<Track_Clientes> Track_Clientes { get; set; }
        public DbSet<Usuario> Usuario { get; set; }
        public DbSet<Track_PuntosRutaSegura> Track_PuntosRutaSegura { get; set; }
        public DbSet<Track_RutaSegura> Track_RutaSegura { get; set; }
    
        //public virtual ObjectResult<Track_ValidarUsuario_Result> Track_ValidarUsuario(string usuario, string password)
        //{
        //    ((IObjectContextAdapter)this).ObjectContext.MetadataWorkspace.LoadFromAssembly(typeof(Track_ValidarUsuario_Result).Assembly);
    
        //    var usuarioParameter = usuario != null ?
        //        new ObjectParameter("Usuario", usuario) :
        //        new ObjectParameter("Usuario", typeof(string));
    
        //    var passwordParameter = password != null ?
        //        new ObjectParameter("Password", password) :
        //        new ObjectParameter("Password", typeof(string));
    
        //    return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Track_ValidarUsuario_Result>("Track_ValidarUsuario", usuarioParameter, passwordParameter);
        //}
    
        public virtual ObjectResult<Track_GetZonas_Result> Track_GetZonas(Nullable<int> idTipoZona, string nombreZona)
        {
            ((IObjectContextAdapter)this).ObjectContext.MetadataWorkspace.LoadFromAssembly(typeof(Track_GetZonas_Result).Assembly);
    
            var idTipoZonaParameter = idTipoZona.HasValue ?
                new ObjectParameter("idTipoZona", idTipoZona) :
                new ObjectParameter("idTipoZona", typeof(int));
    
            var nombreZonaParameter = nombreZona != null ?
                new ObjectParameter("nombreZona", nombreZona) :
                new ObjectParameter("nombreZona", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Track_GetZonas_Result>("Track_GetZonas", idTipoZonaParameter, nombreZonaParameter);
        }
    
        public virtual ObjectResult<string> Track_EliminarZona(Nullable<int> idTipoZona)
        {
            var idTipoZonaParameter = idTipoZona.HasValue ?
                new ObjectParameter("idTipoZona", idTipoZona) :
                new ObjectParameter("idTipoZona", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("Track_EliminarZona", idTipoZonaParameter);
        }
    
        public virtual ObjectResult<Track_GetNroTransportesRuta_Result> Track_GetNroTransportesRuta()
        {
            ((IObjectContextAdapter)this).ObjectContext.MetadataWorkspace.LoadFromAssembly(typeof(Track_GetNroTransportesRuta_Result).Assembly);
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Track_GetNroTransportesRuta_Result>("Track_GetNroTransportesRuta");
        }
    
        public virtual ObjectResult<Track_GetPatentesRuta_Result> Track_GetPatentesRuta()
        {
            ((IObjectContextAdapter)this).ObjectContext.MetadataWorkspace.LoadFromAssembly(typeof(Track_GetPatentesRuta_Result).Assembly);
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Track_GetPatentesRuta_Result>("Track_GetPatentesRuta");
        }
    
        public virtual ObjectResult<Track_GetAlertasRuta_Result> Track_GetAlertasRuta(Nullable<int> nroTransporte, Nullable<int> destino, string estadoViaje)
        {
            ((IObjectContextAdapter)this).ObjectContext.MetadataWorkspace.LoadFromAssembly(typeof(Track_GetAlertasRuta_Result).Assembly);
    
            var nroTransporteParameter = nroTransporte.HasValue ?
                new ObjectParameter("nroTransporte", nroTransporte) :
                new ObjectParameter("nroTransporte", typeof(int));
    
            var destinoParameter = destino.HasValue ?
                new ObjectParameter("destino", destino) :
                new ObjectParameter("destino", typeof(int));
    
            var estadoViajeParameter = estadoViaje != null ?
                new ObjectParameter("estadoViaje", estadoViaje) :
                new ObjectParameter("estadoViaje", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Track_GetAlertasRuta_Result>("Track_GetAlertasRuta", nroTransporteParameter, destinoParameter, estadoViajeParameter);
        }
    
        public virtual ObjectResult<Track_GetPosicionesRuta_Result> Track_GetPosicionesRuta(string patenteTracto, string patenteTrailer, Nullable<System.DateTime> fechaHoraCreacion, Nullable<System.DateTime> fechaHoraSalidaOrigen, Nullable<System.DateTime> fechaHoraLlegadaDestino, Nullable<int> nroTransporte, Nullable<int> destino, string estadoViaje)
        {
            ((IObjectContextAdapter)this).ObjectContext.MetadataWorkspace.LoadFromAssembly(typeof(Track_GetPosicionesRuta_Result).Assembly);
    
            var patenteTractoParameter = patenteTracto != null ?
                new ObjectParameter("patenteTracto", patenteTracto) :
                new ObjectParameter("patenteTracto", typeof(string));
    
            var patenteTrailerParameter = patenteTrailer != null ?
                new ObjectParameter("patenteTrailer", patenteTrailer) :
                new ObjectParameter("patenteTrailer", typeof(string));
    
            var fechaHoraCreacionParameter = fechaHoraCreacion.HasValue ?
                new ObjectParameter("fechaHoraCreacion", fechaHoraCreacion) :
                new ObjectParameter("fechaHoraCreacion", typeof(System.DateTime));
    
            var fechaHoraSalidaOrigenParameter = fechaHoraSalidaOrigen.HasValue ?
                new ObjectParameter("fechaHoraSalidaOrigen", fechaHoraSalidaOrigen) :
                new ObjectParameter("fechaHoraSalidaOrigen", typeof(System.DateTime));
    
            var fechaHoraLlegadaDestinoParameter = fechaHoraLlegadaDestino.HasValue ?
                new ObjectParameter("fechaHoraLlegadaDestino", fechaHoraLlegadaDestino) :
                new ObjectParameter("fechaHoraLlegadaDestino", typeof(System.DateTime));
    
            var nroTransporteParameter = nroTransporte.HasValue ?
                new ObjectParameter("nroTransporte", nroTransporte) :
                new ObjectParameter("nroTransporte", typeof(int));
    
            var destinoParameter = destino.HasValue ?
                new ObjectParameter("destino", destino) :
                new ObjectParameter("destino", typeof(int));
    
            var estadoViajeParameter = estadoViaje != null ?
                new ObjectParameter("estadoViaje", estadoViaje) :
                new ObjectParameter("estadoViaje", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Track_GetPosicionesRuta_Result>("Track_GetPosicionesRuta", patenteTractoParameter, patenteTrailerParameter, fechaHoraCreacionParameter, fechaHoraSalidaOrigenParameter, fechaHoraLlegadaDestinoParameter, nroTransporteParameter, destinoParameter, estadoViajeParameter);
        }
    
        public virtual ObjectResult<Track_GetTransportistasRuta_Result> Track_GetTransportistasRuta()
        {
            ((IObjectContextAdapter)this).ObjectContext.MetadataWorkspace.LoadFromAssembly(typeof(Track_GetTransportistasRuta_Result).Assembly);
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Track_GetTransportistasRuta_Result>("Track_GetTransportistasRuta");
        }
    
        public virtual ObjectResult<Track_GetPosicionesGPS_Result> Track_GetPosicionesGPS(Nullable<System.DateTime> fechaInicio, Nullable<System.DateTime> fechaFin, string patente)
        {
            ((IObjectContextAdapter)this).ObjectContext.MetadataWorkspace.LoadFromAssembly(typeof(Track_GetPosicionesGPS_Result).Assembly);
    
            var fechaInicioParameter = fechaInicio.HasValue ?
                new ObjectParameter("FechaInicio", fechaInicio) :
                new ObjectParameter("FechaInicio", typeof(System.DateTime));
    
            var fechaFinParameter = fechaFin.HasValue ?
                new ObjectParameter("FechaFin", fechaFin) :
                new ObjectParameter("FechaFin", typeof(System.DateTime));
    
            var patenteParameter = patente != null ?
                new ObjectParameter("Patente", patente) :
                new ObjectParameter("Patente", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Track_GetPosicionesGPS_Result>("Track_GetPosicionesGPS", fechaInicioParameter, fechaFinParameter, patenteParameter);
        }
    
        public virtual ObjectResult<Track_GetPosicionesGPS_Ruta_Result> Track_GetPosicionesGPS_Ruta(Nullable<System.DateTime> fechaInicio, Nullable<System.DateTime> fechaFin, string patente)
        {
            ((IObjectContextAdapter)this).ObjectContext.MetadataWorkspace.LoadFromAssembly(typeof(Track_GetPosicionesGPS_Ruta_Result).Assembly);
    
            var fechaInicioParameter = fechaInicio.HasValue ?
                new ObjectParameter("FechaInicio", fechaInicio) :
                new ObjectParameter("FechaInicio", typeof(System.DateTime));
    
            var fechaFinParameter = fechaFin.HasValue ?
                new ObjectParameter("FechaFin", fechaFin) :
                new ObjectParameter("FechaFin", typeof(System.DateTime));
    
            var patenteParameter = patente != null ?
                new ObjectParameter("Patente", patente) :
                new ObjectParameter("Patente", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Track_GetPosicionesGPS_Ruta_Result>("Track_GetPosicionesGPS_Ruta", fechaInicioParameter, fechaFinParameter, patenteParameter);
        }
    
        public virtual ObjectResult<Track_GetZonasToDraw_Result> Track_GetZonasToDraw(Nullable<System.DateTime> fechaDesde, Nullable<System.DateTime> fechaHasta, string patente1, string patente2, Nullable<int> nroTransporte)
        {
            ((IObjectContextAdapter)this).ObjectContext.MetadataWorkspace.LoadFromAssembly(typeof(Track_GetZonasToDraw_Result).Assembly);
    
            var fechaDesdeParameter = fechaDesde.HasValue ?
                new ObjectParameter("fechaDesde", fechaDesde) :
                new ObjectParameter("fechaDesde", typeof(System.DateTime));
    
            var fechaHastaParameter = fechaHasta.HasValue ?
                new ObjectParameter("fechaHasta", fechaHasta) :
                new ObjectParameter("fechaHasta", typeof(System.DateTime));
    
            var patente1Parameter = patente1 != null ?
                new ObjectParameter("patente1", patente1) :
                new ObjectParameter("patente1", typeof(string));
    
            var patente2Parameter = patente2 != null ?
                new ObjectParameter("patente2", patente2) :
                new ObjectParameter("patente2", typeof(string));
    
            var nroTransporteParameter = nroTransporte.HasValue ?
                new ObjectParameter("NroTransporte", nroTransporte) :
                new ObjectParameter("NroTransporte", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Track_GetZonasToDraw_Result>("Track_GetZonasToDraw", fechaDesdeParameter, fechaHastaParameter, patente1Parameter, patente2Parameter, nroTransporteParameter);
        }
    
        public virtual ObjectResult<Track_GetInformeViajes_Result> Track_GetInformeViajes(Nullable<System.DateTime> desde, Nullable<System.DateTime> hasta, string transportista, string patente, Nullable<int> nroTransporte, Nullable<int> nroOS, string userName, string tipoEtis)
        {
            ((IObjectContextAdapter)this).ObjectContext.MetadataWorkspace.LoadFromAssembly(typeof(Track_GetInformeViajes_Result).Assembly);
    
            var desdeParameter = desde.HasValue ?
                new ObjectParameter("desde", desde) :
                new ObjectParameter("desde", typeof(System.DateTime));
    
            var hastaParameter = hasta.HasValue ?
                new ObjectParameter("hasta", hasta) :
                new ObjectParameter("hasta", typeof(System.DateTime));
    
            var transportistaParameter = transportista != null ?
                new ObjectParameter("transportista", transportista) :
                new ObjectParameter("transportista", typeof(string));
    
            var patenteParameter = patente != null ?
                new ObjectParameter("patente", patente) :
                new ObjectParameter("patente", typeof(string));
    
            var nroTransporteParameter = nroTransporte.HasValue ?
                new ObjectParameter("nroTransporte", nroTransporte) :
                new ObjectParameter("nroTransporte", typeof(int));
    
            var nroOSParameter = nroOS.HasValue ?
                new ObjectParameter("nroOS", nroOS) :
                new ObjectParameter("nroOS", typeof(int));
    
            var userNameParameter = userName != null ?
                new ObjectParameter("userName", userName) :
                new ObjectParameter("userName", typeof(string));
    
            var tipoEtisParameter = tipoEtis != null ?
                new ObjectParameter("tipoEtis", tipoEtis) :
                new ObjectParameter("tipoEtis", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Track_GetInformeViajes_Result>("Track_GetInformeViajes", desdeParameter, hastaParameter, transportistaParameter, patenteParameter, nroTransporteParameter, nroOSParameter, userNameParameter, tipoEtisParameter);
        }
    
        public virtual ObjectResult<Track_UpdateObservacionesInformeViaje_Result> Track_UpdateObservacionesInformeViaje(Nullable<int> idAlerta, Nullable<int> nroTransporte, string observaciones)
        {
            ((IObjectContextAdapter)this).ObjectContext.MetadataWorkspace.LoadFromAssembly(typeof(Track_UpdateObservacionesInformeViaje_Result).Assembly);
    
            var idAlertaParameter = idAlerta.HasValue ?
                new ObjectParameter("idAlerta", idAlerta) :
                new ObjectParameter("idAlerta", typeof(int));
    
            var nroTransporteParameter = nroTransporte.HasValue ?
                new ObjectParameter("nroTransporte", nroTransporte) :
                new ObjectParameter("nroTransporte", typeof(int));
    
            var observacionesParameter = observaciones != null ?
                new ObjectParameter("observaciones", observaciones) :
                new ObjectParameter("observaciones", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Track_UpdateObservacionesInformeViaje_Result>("Track_UpdateObservacionesInformeViaje", idAlertaParameter, nroTransporteParameter, observacionesParameter);
        }
    
        public virtual ObjectResult<Track_GetDetalleTrayecto_Result> Track_GetDetalleTrayecto(Nullable<int> nroTransporte)
        {
            ((IObjectContextAdapter)this).ObjectContext.MetadataWorkspace.LoadFromAssembly(typeof(Track_GetDetalleTrayecto_Result).Assembly);
    
            var nroTransporteParameter = nroTransporte.HasValue ?
                new ObjectParameter("nroTransporte", nroTransporte) :
                new ObjectParameter("nroTransporte", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Track_GetDetalleTrayecto_Result>("Track_GetDetalleTrayecto", nroTransporteParameter);
        }
    
        public virtual ObjectResult<Track_GetNroTransportes_Result> Track_GetNroTransportes(Nullable<System.DateTime> desde, Nullable<System.DateTime> hasta)
        {
            ((IObjectContextAdapter)this).ObjectContext.MetadataWorkspace.LoadFromAssembly(typeof(Track_GetNroTransportes_Result).Assembly);
    
            var desdeParameter = desde.HasValue ?
                new ObjectParameter("desde", desde) :
                new ObjectParameter("desde", typeof(System.DateTime));
    
            var hastaParameter = hasta.HasValue ?
                new ObjectParameter("hasta", hasta) :
                new ObjectParameter("hasta", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Track_GetNroTransportes_Result>("Track_GetNroTransportes", desdeParameter, hastaParameter);
        }
    
        public virtual ObjectResult<Track_GetViajesHistoricos_Result> Track_GetViajesHistoricos(Nullable<System.DateTime> desde, Nullable<System.DateTime> hasta, Nullable<int> nroTransporte, string nroContenedor, string patente, string estadoViaje, string userName, string tipoEtis)
        {
            ((IObjectContextAdapter)this).ObjectContext.MetadataWorkspace.LoadFromAssembly(typeof(Track_GetViajesHistoricos_Result).Assembly);
    
            var desdeParameter = desde.HasValue ?
                new ObjectParameter("desde", desde) :
                new ObjectParameter("desde", typeof(System.DateTime));
    
            var hastaParameter = hasta.HasValue ?
                new ObjectParameter("hasta", hasta) :
                new ObjectParameter("hasta", typeof(System.DateTime));
    
            var nroTransporteParameter = nroTransporte.HasValue ?
                new ObjectParameter("nroTransporte", nroTransporte) :
                new ObjectParameter("nroTransporte", typeof(int));
    
            var nroContenedorParameter = nroContenedor != null ?
                new ObjectParameter("nroContenedor", nroContenedor) :
                new ObjectParameter("nroContenedor", typeof(string));
    
            var patenteParameter = patente != null ?
                new ObjectParameter("patente", patente) :
                new ObjectParameter("patente", typeof(string));
    
            var estadoViajeParameter = estadoViaje != null ?
                new ObjectParameter("estadoViaje", estadoViaje) :
                new ObjectParameter("estadoViaje", typeof(string));
    
            var userNameParameter = userName != null ?
                new ObjectParameter("userName", userName) :
                new ObjectParameter("userName", typeof(string));
    
            var tipoEtisParameter = tipoEtis != null ?
                new ObjectParameter("tipoEtis", tipoEtis) :
                new ObjectParameter("tipoEtis", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Track_GetViajesHistoricos_Result>("Track_GetViajesHistoricos", desdeParameter, hastaParameter, nroTransporteParameter, nroContenedorParameter, patenteParameter, estadoViajeParameter, userNameParameter, tipoEtisParameter);
        }
    
        public virtual ObjectResult<Track_GetRutas_Result> Track_GetRutas()
        {
            ((IObjectContextAdapter)this).ObjectContext.MetadataWorkspace.LoadFromAssembly(typeof(Track_GetRutas_Result).Assembly);
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Track_GetRutas_Result>("Track_GetRutas");
        }
    
        public virtual ObjectResult<string> Track_EliminarRuta(Nullable<int> idRuta)
        {
            var idRutaParameter = idRuta.HasValue ?
                new ObjectParameter("idRuta", idRuta) :
                new ObjectParameter("idRuta", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("Track_EliminarRuta", idRutaParameter);
        }
    
        public virtual ObjectResult<Track_RutaOptima_Result> Track_RutaOptima(Nullable<int> criterioOptimizacion, string stringRuta1, string stringRuta2, string stringRuta3, string stringRuta4, string stringRuta5)
        {
            ((IObjectContextAdapter)this).ObjectContext.MetadataWorkspace.LoadFromAssembly(typeof(Track_RutaOptima_Result).Assembly);
    
            var criterioOptimizacionParameter = criterioOptimizacion.HasValue ?
                new ObjectParameter("criterioOptimizacion", criterioOptimizacion) :
                new ObjectParameter("criterioOptimizacion", typeof(int));
    
            var stringRuta1Parameter = stringRuta1 != null ?
                new ObjectParameter("stringRuta1", stringRuta1) :
                new ObjectParameter("stringRuta1", typeof(string));
    
            var stringRuta2Parameter = stringRuta2 != null ?
                new ObjectParameter("stringRuta2", stringRuta2) :
                new ObjectParameter("stringRuta2", typeof(string));
    
            var stringRuta3Parameter = stringRuta3 != null ?
                new ObjectParameter("stringRuta3", stringRuta3) :
                new ObjectParameter("stringRuta3", typeof(string));
    
            var stringRuta4Parameter = stringRuta4 != null ?
                new ObjectParameter("stringRuta4", stringRuta4) :
                new ObjectParameter("stringRuta4", typeof(string));
    
            var stringRuta5Parameter = stringRuta5 != null ?
                new ObjectParameter("stringRuta5", stringRuta5) :
                new ObjectParameter("stringRuta5", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Track_RutaOptima_Result>("Track_RutaOptima", criterioOptimizacionParameter, stringRuta1Parameter, stringRuta2Parameter, stringRuta3Parameter, stringRuta4Parameter, stringRuta5Parameter);
        }
    
        public virtual ObjectResult<Track_GetViajesAsignados_Result> Track_GetViajesAsignados()
        {
            ((IObjectContextAdapter)this).ObjectContext.MetadataWorkspace.LoadFromAssembly(typeof(Track_GetViajesAsignados_Result).Assembly);
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Track_GetViajesAsignados_Result>("Track_GetViajesAsignados");
        }
    
        public virtual ObjectResult<Track_GetRpt_KmsRecorridos_Result> Track_GetRpt_KmsRecorridos(Nullable<System.DateTime> desde, Nullable<System.DateTime> hasta, string transportista, string patente)
        {
            ((IObjectContextAdapter)this).ObjectContext.MetadataWorkspace.LoadFromAssembly(typeof(Track_GetRpt_KmsRecorridos_Result).Assembly);
    
            var desdeParameter = desde.HasValue ?
                new ObjectParameter("desde", desde) :
                new ObjectParameter("desde", typeof(System.DateTime));
    
            var hastaParameter = hasta.HasValue ?
                new ObjectParameter("hasta", hasta) :
                new ObjectParameter("hasta", typeof(System.DateTime));
    
            var transportistaParameter = transportista != null ?
                new ObjectParameter("transportista", transportista) :
                new ObjectParameter("transportista", typeof(string));
    
            var patenteParameter = patente != null ?
                new ObjectParameter("patente", patente) :
                new ObjectParameter("patente", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Track_GetRpt_KmsRecorridos_Result>("Track_GetRpt_KmsRecorridos", desdeParameter, hastaParameter, transportistaParameter, patenteParameter);
        }
    
        public virtual ObjectResult<Track_GeneraRutaOptima_Result> Track_GeneraRutaOptima(Nullable<int> criterioOptimizacion, string latOrigen, string lonOrigen, string latDestino, string lonDestino, string stringRuta1, string stringRuta2, string stringRuta3, string stringRuta4, string stringRuta5)
        {
            ((IObjectContextAdapter)this).ObjectContext.MetadataWorkspace.LoadFromAssembly(typeof(Track_GeneraRutaOptima_Result).Assembly);
    
            var criterioOptimizacionParameter = criterioOptimizacion.HasValue ?
                new ObjectParameter("criterioOptimizacion", criterioOptimizacion) :
                new ObjectParameter("criterioOptimizacion", typeof(int));
    
            var latOrigenParameter = latOrigen != null ?
                new ObjectParameter("latOrigen", latOrigen) :
                new ObjectParameter("latOrigen", typeof(string));
    
            var lonOrigenParameter = lonOrigen != null ?
                new ObjectParameter("lonOrigen", lonOrigen) :
                new ObjectParameter("lonOrigen", typeof(string));
    
            var latDestinoParameter = latDestino != null ?
                new ObjectParameter("latDestino", latDestino) :
                new ObjectParameter("latDestino", typeof(string));
    
            var lonDestinoParameter = lonDestino != null ?
                new ObjectParameter("lonDestino", lonDestino) :
                new ObjectParameter("lonDestino", typeof(string));
    
            var stringRuta1Parameter = stringRuta1 != null ?
                new ObjectParameter("stringRuta1", stringRuta1) :
                new ObjectParameter("stringRuta1", typeof(string));
    
            var stringRuta2Parameter = stringRuta2 != null ?
                new ObjectParameter("stringRuta2", stringRuta2) :
                new ObjectParameter("stringRuta2", typeof(string));
    
            var stringRuta3Parameter = stringRuta3 != null ?
                new ObjectParameter("stringRuta3", stringRuta3) :
                new ObjectParameter("stringRuta3", typeof(string));
    
            var stringRuta4Parameter = stringRuta4 != null ?
                new ObjectParameter("stringRuta4", stringRuta4) :
                new ObjectParameter("stringRuta4", typeof(string));
    
            var stringRuta5Parameter = stringRuta5 != null ?
                new ObjectParameter("stringRuta5", stringRuta5) :
                new ObjectParameter("stringRuta5", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Track_GeneraRutaOptima_Result>("Track_GeneraRutaOptima", criterioOptimizacionParameter, latOrigenParameter, lonOrigenParameter, latDestinoParameter, lonDestinoParameter, stringRuta1Parameter, stringRuta2Parameter, stringRuta3Parameter, stringRuta4Parameter, stringRuta5Parameter);
        }
    
        public virtual ObjectResult<Track_GetAlertasInformeViaje_Result> Track_GetAlertasInformeViaje(Nullable<int> nroTransporte)
        {
            ((IObjectContextAdapter)this).ObjectContext.MetadataWorkspace.LoadFromAssembly(typeof(Track_GetAlertasInformeViaje_Result).Assembly);
    
            var nroTransporteParameter = nroTransporte.HasValue ?
                new ObjectParameter("nroTransporte", nroTransporte) :
                new ObjectParameter("nroTransporte", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Track_GetAlertasInformeViaje_Result>("Track_GetAlertasInformeViaje", nroTransporteParameter);
        }
    
        public virtual ObjectResult<Track_GetGestionCallCenter_Result> Track_GetGestionCallCenter(Nullable<int> nroTransporte, Nullable<int> codLocal)
        {
            ((IObjectContextAdapter)this).ObjectContext.MetadataWorkspace.LoadFromAssembly(typeof(Track_GetGestionCallCenter_Result).Assembly);
    
            var nroTransporteParameter = nroTransporte.HasValue ?
                new ObjectParameter("nroTransporte", nroTransporte) :
                new ObjectParameter("nroTransporte", typeof(int));
    
            var codLocalParameter = codLocal.HasValue ?
                new ObjectParameter("codLocal", codLocal) :
                new ObjectParameter("codLocal", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Track_GetGestionCallCenter_Result>("Track_GetGestionCallCenter", nroTransporteParameter, codLocalParameter);
        }
    
        public virtual ObjectResult<Track_GetAlertasPorGestionarCallCenter_Result> Track_GetAlertasPorGestionarCallCenter(Nullable<int> nroTransporte, Nullable<int> localDestino)
        {
            ((IObjectContextAdapter)this).ObjectContext.MetadataWorkspace.LoadFromAssembly(typeof(Track_GetAlertasPorGestionarCallCenter_Result).Assembly);
    
            var nroTransporteParameter = nroTransporte.HasValue ?
                new ObjectParameter("nroTransporte", nroTransporte) :
                new ObjectParameter("nroTransporte", typeof(int));
    
            var localDestinoParameter = localDestino.HasValue ?
                new ObjectParameter("localDestino", localDestino) :
                new ObjectParameter("localDestino", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Track_GetAlertasPorGestionarCallCenter_Result>("Track_GetAlertasPorGestionarCallCenter", nroTransporteParameter, localDestinoParameter);
        }
    
        public virtual ObjectResult<Track_GetViajesRuta_Result> Track_GetViajesRuta(Nullable<int> nroTransporte, string patente, string estadoViaje, string transportista)
        {
            ((IObjectContextAdapter)this).ObjectContext.MetadataWorkspace.LoadFromAssembly(typeof(Track_GetViajesRuta_Result).Assembly);
    
            var nroTransporteParameter = nroTransporte.HasValue ?
                new ObjectParameter("nroTransporte", nroTransporte) :
                new ObjectParameter("nroTransporte", typeof(int));
    
            var patenteParameter = patente != null ?
                new ObjectParameter("patente", patente) :
                new ObjectParameter("patente", typeof(string));
    
            var estadoViajeParameter = estadoViaje != null ?
                new ObjectParameter("estadoViaje", estadoViaje) :
                new ObjectParameter("estadoViaje", typeof(string));
    
            var transportistaParameter = transportista != null ?
                new ObjectParameter("transportista", transportista) :
                new ObjectParameter("transportista", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Track_GetViajesRuta_Result>("Track_GetViajesRuta", nroTransporteParameter, patenteParameter, estadoViajeParameter, transportistaParameter);
        }
    
        public virtual ObjectResult<Track_GetDashboard_Result> Track_GetDashboard(Nullable<int> year, Nullable<int> month, string transportista)
        {
            ((IObjectContextAdapter)this).ObjectContext.MetadataWorkspace.LoadFromAssembly(typeof(Track_GetDashboard_Result).Assembly);
    
            var yearParameter = year.HasValue ?
                new ObjectParameter("year", year) :
                new ObjectParameter("year", typeof(int));
    
            var monthParameter = month.HasValue ?
                new ObjectParameter("month", month) :
                new ObjectParameter("month", typeof(int));
    
            var transportistaParameter = transportista != null ?
                new ObjectParameter("transportista", transportista) :
                new ObjectParameter("transportista", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Track_GetDashboard_Result>("Track_GetDashboard", yearParameter, monthParameter, transportistaParameter);
        }
    
        public virtual ObjectResult<Track_EliminarViaje_Result> Track_EliminarViaje(Nullable<int> nroTransporte, Nullable<int> codLocal)
        {
            ((IObjectContextAdapter)this).ObjectContext.MetadataWorkspace.LoadFromAssembly(typeof(Track_EliminarViaje_Result).Assembly);
    
            var nroTransporteParameter = nroTransporte.HasValue ?
                new ObjectParameter("nroTransporte", nroTransporte) :
                new ObjectParameter("nroTransporte", typeof(int));
    
            var codLocalParameter = codLocal.HasValue ?
                new ObjectParameter("codLocal", codLocal) :
                new ObjectParameter("codLocal", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Track_EliminarViaje_Result>("Track_EliminarViaje", nroTransporteParameter, codLocalParameter);
        }
    
        public virtual ObjectResult<Track_ValidarMovilCD_Result> Track_ValidarMovilCD(string patente)
        {
            ((IObjectContextAdapter)this).ObjectContext.MetadataWorkspace.LoadFromAssembly(typeof(Track_ValidarMovilCD_Result).Assembly);
    
            var patenteParameter = patente != null ?
                new ObjectParameter("patente", patente) :
                new ObjectParameter("patente", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Track_ValidarMovilCD_Result>("Track_ValidarMovilCD", patenteParameter);
        }
    
        public virtual ObjectResult<Track_EditarViaje_Result> Track_EditarViaje(Nullable<int> nroTransporte, string transportista, string trailer, string tracto, Nullable<int> codOrigen, Nullable<int> codDestino, string rutConductor, string nombreConductor)
        {
            ((IObjectContextAdapter)this).ObjectContext.MetadataWorkspace.LoadFromAssembly(typeof(Track_EditarViaje_Result).Assembly);
    
            var nroTransporteParameter = nroTransporte.HasValue ?
                new ObjectParameter("nroTransporte", nroTransporte) :
                new ObjectParameter("nroTransporte", typeof(int));
    
            var transportistaParameter = transportista != null ?
                new ObjectParameter("transportista", transportista) :
                new ObjectParameter("transportista", typeof(string));
    
            var trailerParameter = trailer != null ?
                new ObjectParameter("trailer", trailer) :
                new ObjectParameter("trailer", typeof(string));
    
            var tractoParameter = tracto != null ?
                new ObjectParameter("tracto", tracto) :
                new ObjectParameter("tracto", typeof(string));
    
            var codOrigenParameter = codOrigen.HasValue ?
                new ObjectParameter("codOrigen", codOrigen) :
                new ObjectParameter("codOrigen", typeof(int));
    
            var codDestinoParameter = codDestino.HasValue ?
                new ObjectParameter("codDestino", codDestino) :
                new ObjectParameter("codDestino", typeof(int));
    
            var rutConductorParameter = rutConductor != null ?
                new ObjectParameter("rutConductor", rutConductor) :
                new ObjectParameter("rutConductor", typeof(string));
    
            var nombreConductorParameter = nombreConductor != null ?
                new ObjectParameter("nombreConductor", nombreConductor) :
                new ObjectParameter("nombreConductor", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Track_EditarViaje_Result>("Track_EditarViaje", nroTransporteParameter, transportistaParameter, trailerParameter, tractoParameter, codOrigenParameter, codDestinoParameter, rutConductorParameter, nombreConductorParameter);
        }
    
        public virtual ObjectResult<Track_GetAlertasRutaModuloMapa_Result> Track_GetAlertasRutaModuloMapa(Nullable<int> idAlerta)
        {
            ((IObjectContextAdapter)this).ObjectContext.MetadataWorkspace.LoadFromAssembly(typeof(Track_GetAlertasRutaModuloMapa_Result).Assembly);
    
            var idAlertaParameter = idAlerta.HasValue ?
                new ObjectParameter("IdAlerta", idAlerta) :
                new ObjectParameter("IdAlerta", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Track_GetAlertasRutaModuloMapa_Result>("Track_GetAlertasRutaModuloMapa", idAlertaParameter);
        }
    
        public virtual ObjectResult<Track_GetPosicionesRutaModuloMapa_Result> Track_GetPosicionesRutaModuloMapa(Nullable<int> idAlerta)
        {
            ((IObjectContextAdapter)this).ObjectContext.MetadataWorkspace.LoadFromAssembly(typeof(Track_GetPosicionesRutaModuloMapa_Result).Assembly);
    
            var idAlertaParameter = idAlerta.HasValue ?
                new ObjectParameter("IdAlerta", idAlerta) :
                new ObjectParameter("IdAlerta", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Track_GetPosicionesRutaModuloMapa_Result>("Track_GetPosicionesRutaModuloMapa", idAlertaParameter);
        }
    
        public virtual ObjectResult<Track_GetZonasToDrawModuloMapa_Result> Track_GetZonasToDrawModuloMapa(Nullable<int> idAlerta)
        {
            ((IObjectContextAdapter)this).ObjectContext.MetadataWorkspace.LoadFromAssembly(typeof(Track_GetZonasToDrawModuloMapa_Result).Assembly);
    
            var idAlertaParameter = idAlerta.HasValue ?
                new ObjectParameter("IdAlerta", idAlerta) :
                new ObjectParameter("IdAlerta", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Track_GetZonasToDrawModuloMapa_Result>("Track_GetZonasToDrawModuloMapa", idAlertaParameter);
        }
    
        public virtual ObjectResult<Track_GetProveedoresGPS_Result> Track_GetProveedoresGPS(string rutTransportista)
        {
            ((IObjectContextAdapter)this).ObjectContext.MetadataWorkspace.LoadFromAssembly(typeof(Track_GetProveedoresGPS_Result).Assembly);
    
            var rutTransportistaParameter = rutTransportista != null ?
                new ObjectParameter("rutTransportista", rutTransportista) :
                new ObjectParameter("rutTransportista", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Track_GetProveedoresGPS_Result>("Track_GetProveedoresGPS", rutTransportistaParameter);
        }
    
        public virtual ObjectResult<Track_GetRpt_Alertas_Result> Track_GetRpt_Alertas(Nullable<System.DateTime> desde, Nullable<System.DateTime> hasta, string transportista, string patente, string scoreConductor, string rutConductor, string tipoAlerta, Nullable<int> idFormato, Nullable<int> codigoDestino, string permiso, string estadoViaje, string proveedorGPS)
        {
            ((IObjectContextAdapter)this).ObjectContext.MetadataWorkspace.LoadFromAssembly(typeof(Track_GetRpt_Alertas_Result).Assembly);
    
            var desdeParameter = desde.HasValue ?
                new ObjectParameter("desde", desde) :
                new ObjectParameter("desde", typeof(System.DateTime));
    
            var hastaParameter = hasta.HasValue ?
                new ObjectParameter("hasta", hasta) :
                new ObjectParameter("hasta", typeof(System.DateTime));
    
            var transportistaParameter = transportista != null ?
                new ObjectParameter("transportista", transportista) :
                new ObjectParameter("transportista", typeof(string));
    
            var patenteParameter = patente != null ?
                new ObjectParameter("patente", patente) :
                new ObjectParameter("patente", typeof(string));
    
            var scoreConductorParameter = scoreConductor != null ?
                new ObjectParameter("scoreConductor", scoreConductor) :
                new ObjectParameter("scoreConductor", typeof(string));
    
            var rutConductorParameter = rutConductor != null ?
                new ObjectParameter("rutConductor", rutConductor) :
                new ObjectParameter("rutConductor", typeof(string));
    
            var tipoAlertaParameter = tipoAlerta != null ?
                new ObjectParameter("tipoAlerta", tipoAlerta) :
                new ObjectParameter("tipoAlerta", typeof(string));
    
            var idFormatoParameter = idFormato.HasValue ?
                new ObjectParameter("idFormato", idFormato) :
                new ObjectParameter("idFormato", typeof(int));
    
            var codigoDestinoParameter = codigoDestino.HasValue ?
                new ObjectParameter("codigoDestino", codigoDestino) :
                new ObjectParameter("codigoDestino", typeof(int));
    
            var permisoParameter = permiso != null ?
                new ObjectParameter("permiso", permiso) :
                new ObjectParameter("permiso", typeof(string));
    
            var estadoViajeParameter = estadoViaje != null ?
                new ObjectParameter("estadoViaje", estadoViaje) :
                new ObjectParameter("estadoViaje", typeof(string));
    
            var proveedorGPSParameter = proveedorGPS != null ?
                new ObjectParameter("proveedorGPS", proveedorGPS) :
                new ObjectParameter("proveedorGPS", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Track_GetRpt_Alertas_Result>("Track_GetRpt_Alertas", desdeParameter, hastaParameter, transportistaParameter, patenteParameter, scoreConductorParameter, rutConductorParameter, tipoAlertaParameter, idFormatoParameter, codigoDestinoParameter, permisoParameter, estadoViajeParameter, proveedorGPSParameter);
        }
    
        public virtual ObjectResult<Track_GetFlotaOnline_Result> Track_GetFlotaOnline(string patente, string transportista, Nullable<int> ignicion, string estadoTrip, string estadoGPS, string proveedorGPS)
        {
            ((IObjectContextAdapter)this).ObjectContext.MetadataWorkspace.LoadFromAssembly(typeof(Track_GetFlotaOnline_Result).Assembly);
    
            var patenteParameter = patente != null ?
                new ObjectParameter("Patente", patente) :
                new ObjectParameter("Patente", typeof(string));
    
            var transportistaParameter = transportista != null ?
                new ObjectParameter("Transportista", transportista) :
                new ObjectParameter("Transportista", typeof(string));
    
            var ignicionParameter = ignicion.HasValue ?
                new ObjectParameter("Ignicion", ignicion) :
                new ObjectParameter("Ignicion", typeof(int));
    
            var estadoTripParameter = estadoTrip != null ?
                new ObjectParameter("estadoTrip", estadoTrip) :
                new ObjectParameter("estadoTrip", typeof(string));
    
            var estadoGPSParameter = estadoGPS != null ?
                new ObjectParameter("estadoGPS", estadoGPS) :
                new ObjectParameter("estadoGPS", typeof(string));
    
            var proveedorGPSParameter = proveedorGPS != null ?
                new ObjectParameter("proveedorGPS", proveedorGPS) :
                new ObjectParameter("proveedorGPS", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Track_GetFlotaOnline_Result>("Track_GetFlotaOnline", patenteParameter, transportistaParameter, ignicionParameter, estadoTripParameter, estadoGPSParameter, proveedorGPSParameter);
        }
    
        public virtual ObjectResult<Track_GetVerticesZona_Result> Track_GetVerticesZona(Nullable<int> idZona)
        {
            ((IObjectContextAdapter)this).ObjectContext.MetadataWorkspace.LoadFromAssembly(typeof(Track_GetVerticesZona_Result).Assembly);
    
            var idZonaParameter = idZona.HasValue ?
                new ObjectParameter("idZona", idZona) :
                new ObjectParameter("idZona", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Track_GetVerticesZona_Result>("Track_GetVerticesZona", idZonaParameter);
        }
    
        public virtual ObjectResult<Track_GetRpt_Alertas_DetalleArea_Result> Track_GetRpt_Alertas_DetalleArea(Nullable<System.DateTime> desde, Nullable<System.DateTime> hasta, string transportista, string patente, string scoreConductor, string rutConductor, string tipoAlerta, Nullable<int> idFormato, Nullable<int> codigoDestino, string permiso, string estadoViaje, string proveedorGPS, string stringPolygon)
        {
            ((IObjectContextAdapter)this).ObjectContext.MetadataWorkspace.LoadFromAssembly(typeof(Track_GetRpt_Alertas_DetalleArea_Result).Assembly);
    
            var desdeParameter = desde.HasValue ?
                new ObjectParameter("desde", desde) :
                new ObjectParameter("desde", typeof(System.DateTime));
    
            var hastaParameter = hasta.HasValue ?
                new ObjectParameter("hasta", hasta) :
                new ObjectParameter("hasta", typeof(System.DateTime));
    
            var transportistaParameter = transportista != null ?
                new ObjectParameter("transportista", transportista) :
                new ObjectParameter("transportista", typeof(string));
    
            var patenteParameter = patente != null ?
                new ObjectParameter("patente", patente) :
                new ObjectParameter("patente", typeof(string));
    
            var scoreConductorParameter = scoreConductor != null ?
                new ObjectParameter("scoreConductor", scoreConductor) :
                new ObjectParameter("scoreConductor", typeof(string));
    
            var rutConductorParameter = rutConductor != null ?
                new ObjectParameter("rutConductor", rutConductor) :
                new ObjectParameter("rutConductor", typeof(string));
    
            var tipoAlertaParameter = tipoAlerta != null ?
                new ObjectParameter("tipoAlerta", tipoAlerta) :
                new ObjectParameter("tipoAlerta", typeof(string));
    
            var idFormatoParameter = idFormato.HasValue ?
                new ObjectParameter("idFormato", idFormato) :
                new ObjectParameter("idFormato", typeof(int));
    
            var codigoDestinoParameter = codigoDestino.HasValue ?
                new ObjectParameter("codigoDestino", codigoDestino) :
                new ObjectParameter("codigoDestino", typeof(int));
    
            var permisoParameter = permiso != null ?
                new ObjectParameter("permiso", permiso) :
                new ObjectParameter("permiso", typeof(string));
    
            var estadoViajeParameter = estadoViaje != null ?
                new ObjectParameter("estadoViaje", estadoViaje) :
                new ObjectParameter("estadoViaje", typeof(string));
    
            var proveedorGPSParameter = proveedorGPS != null ?
                new ObjectParameter("proveedorGPS", proveedorGPS) :
                new ObjectParameter("proveedorGPS", typeof(string));
    
            var stringPolygonParameter = stringPolygon != null ?
                new ObjectParameter("stringPolygon", stringPolygon) :
                new ObjectParameter("stringPolygon", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Track_GetRpt_Alertas_DetalleArea_Result>("Track_GetRpt_Alertas_DetalleArea", desdeParameter, hastaParameter, transportistaParameter, patenteParameter, scoreConductorParameter, rutConductorParameter, tipoAlertaParameter, idFormatoParameter, codigoDestinoParameter, permisoParameter, estadoViajeParameter, proveedorGPSParameter, stringPolygonParameter);
        }
    
        public virtual ObjectResult<string> Track_AgregarDestinoRuta(Nullable<int> idRuta, Nullable<int> idZona)
        {
            var idRutaParameter = idRuta.HasValue ?
                new ObjectParameter("idRuta", idRuta) :
                new ObjectParameter("idRuta", typeof(int));
    
            var idZonaParameter = idZona.HasValue ?
                new ObjectParameter("idZona", idZona) :
                new ObjectParameter("idZona", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("Track_AgregarDestinoRuta", idRutaParameter, idZonaParameter);
        }
    
        public virtual ObjectResult<string> Track_AgregarRutaGenerada(string nombreRuta)
        {
            var nombreRutaParameter = nombreRuta != null ?
                new ObjectParameter("nombreRuta", nombreRuta) :
                new ObjectParameter("nombreRuta", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("Track_AgregarRutaGenerada", nombreRutaParameter);
        }
    
        public virtual ObjectResult<string> Track_EliminarDestinoRuta(Nullable<int> idZona)
        {
            var idZonaParameter = idZona.HasValue ?
                new ObjectParameter("idZona", idZona) :
                new ObjectParameter("idZona", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("Track_EliminarDestinoRuta", idZonaParameter);
        }
    
        public virtual ObjectResult<string> Track_EliminarRutaGenerada(Nullable<int> idRuta)
        {
            var idRutaParameter = idRuta.HasValue ?
                new ObjectParameter("idRuta", idRuta) :
                new ObjectParameter("idRuta", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("Track_EliminarRutaGenerada", idRutaParameter);
        }
    
        public virtual ObjectResult<Track_GetDetalleRuta_Result> Track_GetDetalleRuta(Nullable<int> id_Ruta)
        {
            ((IObjectContextAdapter)this).ObjectContext.MetadataWorkspace.LoadFromAssembly(typeof(Track_GetDetalleRuta_Result).Assembly);
    
            var id_RutaParameter = id_Ruta.HasValue ?
                new ObjectParameter("id_Ruta", id_Ruta) :
                new ObjectParameter("id_Ruta", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Track_GetDetalleRuta_Result>("Track_GetDetalleRuta", id_RutaParameter);
        }
    
        public virtual ObjectResult<Track_GetRutasGeneradas_Result> Track_GetRutasGeneradas(Nullable<int> id_Ruta)
        {
            ((IObjectContextAdapter)this).ObjectContext.MetadataWorkspace.LoadFromAssembly(typeof(Track_GetRutasGeneradas_Result).Assembly);
    
            var id_RutaParameter = id_Ruta.HasValue ?
                new ObjectParameter("id_Ruta", id_Ruta) :
                new ObjectParameter("id_Ruta", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Track_GetRutasGeneradas_Result>("Track_GetRutasGeneradas", id_RutaParameter);
        }
    
        public virtual ObjectResult<Track_NuevoViaje_Result> Track_NuevoViaje(Nullable<int> nroTransporte, string transportista, string trailer, string tracto, Nullable<int> codOrigen, Nullable<int> codRuta, string rutConductor, string nombreConductor)
        {
            ((IObjectContextAdapter)this).ObjectContext.MetadataWorkspace.LoadFromAssembly(typeof(Track_NuevoViaje_Result).Assembly);
    
            var nroTransporteParameter = nroTransporte.HasValue ?
                new ObjectParameter("nroTransporte", nroTransporte) :
                new ObjectParameter("nroTransporte", typeof(int));
    
            var transportistaParameter = transportista != null ?
                new ObjectParameter("transportista", transportista) :
                new ObjectParameter("transportista", typeof(string));
    
            var trailerParameter = trailer != null ?
                new ObjectParameter("trailer", trailer) :
                new ObjectParameter("trailer", typeof(string));
    
            var tractoParameter = tracto != null ?
                new ObjectParameter("tracto", tracto) :
                new ObjectParameter("tracto", typeof(string));
    
            var codOrigenParameter = codOrigen.HasValue ?
                new ObjectParameter("codOrigen", codOrigen) :
                new ObjectParameter("codOrigen", typeof(int));
    
            var codRutaParameter = codRuta.HasValue ?
                new ObjectParameter("codRuta", codRuta) :
                new ObjectParameter("codRuta", typeof(int));
    
            var rutConductorParameter = rutConductor != null ?
                new ObjectParameter("rutConductor", rutConductor) :
                new ObjectParameter("rutConductor", typeof(string));
    
            var nombreConductorParameter = nombreConductor != null ?
                new ObjectParameter("nombreConductor", nombreConductor) :
                new ObjectParameter("nombreConductor", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Track_NuevoViaje_Result>("Track_NuevoViaje", nroTransporteParameter, transportistaParameter, trailerParameter, tractoParameter, codOrigenParameter, codRutaParameter, rutConductorParameter, nombreConductorParameter);
        }
    
        public virtual ObjectResult<Track_NuevoViajeDestinoUnico_Result> Track_NuevoViajeDestinoUnico(Nullable<int> nroTransporte, string transportista, string trailer, string tracto, Nullable<int> codOrigen, Nullable<int> codDestino, string rutConductor, string nombreConductor)
        {
            ((IObjectContextAdapter)this).ObjectContext.MetadataWorkspace.LoadFromAssembly(typeof(Track_NuevoViajeDestinoUnico_Result).Assembly);
    
            var nroTransporteParameter = nroTransporte.HasValue ?
                new ObjectParameter("nroTransporte", nroTransporte) :
                new ObjectParameter("nroTransporte", typeof(int));
    
            var transportistaParameter = transportista != null ?
                new ObjectParameter("transportista", transportista) :
                new ObjectParameter("transportista", typeof(string));
    
            var trailerParameter = trailer != null ?
                new ObjectParameter("trailer", trailer) :
                new ObjectParameter("trailer", typeof(string));
    
            var tractoParameter = tracto != null ?
                new ObjectParameter("tracto", tracto) :
                new ObjectParameter("tracto", typeof(string));
    
            var codOrigenParameter = codOrigen.HasValue ?
                new ObjectParameter("codOrigen", codOrigen) :
                new ObjectParameter("codOrigen", typeof(int));
    
            var codDestinoParameter = codDestino.HasValue ?
                new ObjectParameter("codDestino", codDestino) :
                new ObjectParameter("codDestino", typeof(int));
    
            var rutConductorParameter = rutConductor != null ?
                new ObjectParameter("rutConductor", rutConductor) :
                new ObjectParameter("rutConductor", typeof(string));
    
            var nombreConductorParameter = nombreConductor != null ?
                new ObjectParameter("nombreConductor", nombreConductor) :
                new ObjectParameter("nombreConductor", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Track_NuevoViajeDestinoUnico_Result>("Track_NuevoViajeDestinoUnico", nroTransporteParameter, transportistaParameter, trailerParameter, tractoParameter, codOrigenParameter, codDestinoParameter, rutConductorParameter, nombreConductorParameter);
        }
    
        public virtual ObjectResult<Track_CierreManual_Result> Track_CierreManual(Nullable<int> nroTransporte, Nullable<int> codLocal, string patenteTracto, string patenteTrailer, string estadoLat, string estadoLon, string userName)
        {
            ((IObjectContextAdapter)this).ObjectContext.MetadataWorkspace.LoadFromAssembly(typeof(Track_CierreManual_Result).Assembly);
    
            var nroTransporteParameter = nroTransporte.HasValue ?
                new ObjectParameter("NroTransporte", nroTransporte) :
                new ObjectParameter("NroTransporte", typeof(int));
    
            var codLocalParameter = codLocal.HasValue ?
                new ObjectParameter("CodLocal", codLocal) :
                new ObjectParameter("CodLocal", typeof(int));
    
            var patenteTractoParameter = patenteTracto != null ?
                new ObjectParameter("patenteTracto", patenteTracto) :
                new ObjectParameter("patenteTracto", typeof(string));
    
            var patenteTrailerParameter = patenteTrailer != null ?
                new ObjectParameter("patenteTrailer", patenteTrailer) :
                new ObjectParameter("patenteTrailer", typeof(string));
    
            var estadoLatParameter = estadoLat != null ?
                new ObjectParameter("estadoLat", estadoLat) :
                new ObjectParameter("estadoLat", typeof(string));
    
            var estadoLonParameter = estadoLon != null ?
                new ObjectParameter("estadoLon", estadoLon) :
                new ObjectParameter("estadoLon", typeof(string));
    
            var userNameParameter = userName != null ?
                new ObjectParameter("userName", userName) :
                new ObjectParameter("userName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Track_CierreManual_Result>("Track_CierreManual", nroTransporteParameter, codLocalParameter, patenteTractoParameter, patenteTrailerParameter, estadoLatParameter, estadoLonParameter, userNameParameter);
        }
    
        public virtual ObjectResult<Track_GetViajesControlPanel_Result> Track_GetViajesControlPanel(Nullable<System.DateTime> desde, Nullable<System.DateTime> hasta, Nullable<int> nroTransporte, string nroContenedor, Nullable<int> idOrigen, Nullable<int> idDestino, string patente, string estadoViaje, string alertas, string userName, string tipoEtis)
        {
            ((IObjectContextAdapter)this).ObjectContext.MetadataWorkspace.LoadFromAssembly(typeof(Track_GetViajesControlPanel_Result).Assembly);
    
            var desdeParameter = desde.HasValue ?
                new ObjectParameter("desde", desde) :
                new ObjectParameter("desde", typeof(System.DateTime));
    
            var hastaParameter = hasta.HasValue ?
                new ObjectParameter("hasta", hasta) :
                new ObjectParameter("hasta", typeof(System.DateTime));
    
            var nroTransporteParameter = nroTransporte.HasValue ?
                new ObjectParameter("nroTransporte", nroTransporte) :
                new ObjectParameter("nroTransporte", typeof(int));
    
            var nroContenedorParameter = nroContenedor != null ?
                new ObjectParameter("nroContenedor", nroContenedor) :
                new ObjectParameter("nroContenedor", typeof(string));
    
            var idOrigenParameter = idOrigen.HasValue ?
                new ObjectParameter("idOrigen", idOrigen) :
                new ObjectParameter("idOrigen", typeof(int));
    
            var idDestinoParameter = idDestino.HasValue ?
                new ObjectParameter("idDestino", idDestino) :
                new ObjectParameter("idDestino", typeof(int));
    
            var patenteParameter = patente != null ?
                new ObjectParameter("patente", patente) :
                new ObjectParameter("patente", typeof(string));
    
            var estadoViajeParameter = estadoViaje != null ?
                new ObjectParameter("estadoViaje", estadoViaje) :
                new ObjectParameter("estadoViaje", typeof(string));
    
            var alertasParameter = alertas != null ?
                new ObjectParameter("alertas", alertas) :
                new ObjectParameter("alertas", typeof(string));
    
            var userNameParameter = userName != null ?
                new ObjectParameter("userName", userName) :
                new ObjectParameter("userName", typeof(string));
    
            var tipoEtisParameter = tipoEtis != null ?
                new ObjectParameter("tipoEtis", tipoEtis) :
                new ObjectParameter("tipoEtis", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Track_GetViajesControlPanel_Result>("Track_GetViajesControlPanel", desdeParameter, hastaParameter, nroTransporteParameter, nroContenedorParameter, idOrigenParameter, idDestinoParameter, patenteParameter, estadoViajeParameter, alertasParameter, userNameParameter, tipoEtisParameter);
        }
    
        public virtual ObjectResult<Track_GetGuiasDespacho_Result> Track_GetGuiasDespacho(Nullable<System.DateTime> desde, Nullable<System.DateTime> hasta, Nullable<int> nroGuia, Nullable<int> nroOS, string userName)
        {
            ((IObjectContextAdapter)this).ObjectContext.MetadataWorkspace.LoadFromAssembly(typeof(Track_GetGuiasDespacho_Result).Assembly);
    
            var desdeParameter = desde.HasValue ?
                new ObjectParameter("desde", desde) :
                new ObjectParameter("desde", typeof(System.DateTime));
    
            var hastaParameter = hasta.HasValue ?
                new ObjectParameter("hasta", hasta) :
                new ObjectParameter("hasta", typeof(System.DateTime));
    
            var nroGuiaParameter = nroGuia.HasValue ?
                new ObjectParameter("nroGuia", nroGuia) :
                new ObjectParameter("nroGuia", typeof(int));
    
            var nroOSParameter = nroOS.HasValue ?
                new ObjectParameter("nroOS", nroOS) :
                new ObjectParameter("nroOS", typeof(int));
    
            var userNameParameter = userName != null ?
                new ObjectParameter("userName", userName) :
                new ObjectParameter("userName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Track_GetGuiasDespacho_Result>("Track_GetGuiasDespacho", desdeParameter, hastaParameter, nroGuiaParameter, nroOSParameter, userNameParameter);
        }
    
        public virtual ObjectResult<Track_GetTipoEtis_Result> Track_GetTipoEtis()
        {
            ((IObjectContextAdapter)this).ObjectContext.MetadataWorkspace.LoadFromAssembly(typeof(Track_GetTipoEtis_Result).Assembly);
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Track_GetTipoEtis_Result>("Track_GetTipoEtis");
        }
    
        public virtual ObjectResult<Track_GetDashboardIntegracion_Result> Track_GetDashboardIntegracion()
        {
            ((IObjectContextAdapter)this).ObjectContext.MetadataWorkspace.LoadFromAssembly(typeof(Track_GetDashboardIntegracion_Result).Assembly);
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Track_GetDashboardIntegracion_Result>("Track_GetDashboardIntegracion");
        }
    
        public virtual ObjectResult<Track_GetDashboardAlertas_Result> Track_GetDashboardAlertas()
        {
            ((IObjectContextAdapter)this).ObjectContext.MetadataWorkspace.LoadFromAssembly(typeof(Track_GetDashboardAlertas_Result).Assembly);
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Track_GetDashboardAlertas_Result>("Track_GetDashboardAlertas");
        }
    
        public virtual ObjectResult<Track_GetDashboardMotivos_Result> Track_GetDashboardMotivos()
        {
            ((IObjectContextAdapter)this).ObjectContext.MetadataWorkspace.LoadFromAssembly(typeof(Track_GetDashboardMotivos_Result).Assembly);
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Track_GetDashboardMotivos_Result>("Track_GetDashboardMotivos");
        }
    
        public virtual ObjectResult<Track_GetDashboardTendenciaIntegracion_Result> Track_GetDashboardTendenciaIntegracion()
        {
            ((IObjectContextAdapter)this).ObjectContext.MetadataWorkspace.LoadFromAssembly(typeof(Track_GetDashboardTendenciaIntegracion_Result).Assembly);
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Track_GetDashboardTendenciaIntegracion_Result>("Track_GetDashboardTendenciaIntegracion");
        }
    
        public virtual ObjectResult<Track_GetDashboardTendenciaAlertas_Result> Track_GetDashboardTendenciaAlertas()
        {
            ((IObjectContextAdapter)this).ObjectContext.MetadataWorkspace.LoadFromAssembly(typeof(Track_GetDashboardTendenciaAlertas_Result).Assembly);
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Track_GetDashboardTendenciaAlertas_Result>("Track_GetDashboardTendenciaAlertas");
        }
    
        public virtual ObjectResult<Track_GetEstadoPatente_Result> Track_GetEstadoPatente(string patente)
        {
            ((IObjectContextAdapter)this).ObjectContext.MetadataWorkspace.LoadFromAssembly(typeof(Track_GetEstadoPatente_Result).Assembly);
    
            var patenteParameter = patente != null ?
                new ObjectParameter("patente", patente) :
                new ObjectParameter("patente", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Track_GetEstadoPatente_Result>("Track_GetEstadoPatente", patenteParameter);
        }
    
        public virtual ObjectResult<Track_UpdateCodZonaIdZona_Result> Track_UpdateCodZonaIdZona(string clientesAsociados, Nullable<int> idZona)
        {
            ((IObjectContextAdapter)this).ObjectContext.MetadataWorkspace.LoadFromAssembly(typeof(Track_UpdateCodZonaIdZona_Result).Assembly);
    
            var clientesAsociadosParameter = clientesAsociados != null ?
                new ObjectParameter("clientesAsociados", clientesAsociados) :
                new ObjectParameter("clientesAsociados", typeof(string));
    
            var idZonaParameter = idZona.HasValue ?
                new ObjectParameter("idZona", idZona) :
                new ObjectParameter("idZona", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Track_UpdateCodZonaIdZona_Result>("Track_UpdateCodZonaIdZona", clientesAsociadosParameter, idZonaParameter);
        }
    
        public virtual ObjectResult<Track_GetZonasAsociadas_Result> Track_GetZonasAsociadas(Nullable<int> idTipoZona, string nombreZona)
        {
            ((IObjectContextAdapter)this).ObjectContext.MetadataWorkspace.LoadFromAssembly(typeof(Track_GetZonasAsociadas_Result).Assembly);
    
            var idTipoZonaParameter = idTipoZona.HasValue ?
                new ObjectParameter("idTipoZona", idTipoZona) :
                new ObjectParameter("idTipoZona", typeof(int));
    
            var nombreZonaParameter = nombreZona != null ?
                new ObjectParameter("nombreZona", nombreZona) :
                new ObjectParameter("nombreZona", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Track_GetZonasAsociadas_Result>("Track_GetZonasAsociadas", idTipoZonaParameter, nombreZonaParameter);
        }
    
        public virtual ObjectResult<Track_GetMonitoreoOnline_Result> Track_GetMonitoreoOnline(string patente, string transportista, Nullable<int> ignicion, string estadoTrip, string estadoGPS, string proveedorGPS, Nullable<int> nroViaje, string tipoEtis, string rutCliente)
        {
            ((IObjectContextAdapter)this).ObjectContext.MetadataWorkspace.LoadFromAssembly(typeof(Track_GetMonitoreoOnline_Result).Assembly);
    
            var patenteParameter = patente != null ?
                new ObjectParameter("Patente", patente) :
                new ObjectParameter("Patente", typeof(string));
    
            var transportistaParameter = transportista != null ?
                new ObjectParameter("Transportista", transportista) :
                new ObjectParameter("Transportista", typeof(string));
    
            var ignicionParameter = ignicion.HasValue ?
                new ObjectParameter("Ignicion", ignicion) :
                new ObjectParameter("Ignicion", typeof(int));
    
            var estadoTripParameter = estadoTrip != null ?
                new ObjectParameter("estadoTrip", estadoTrip) :
                new ObjectParameter("estadoTrip", typeof(string));
    
            var estadoGPSParameter = estadoGPS != null ?
                new ObjectParameter("estadoGPS", estadoGPS) :
                new ObjectParameter("estadoGPS", typeof(string));
    
            var proveedorGPSParameter = proveedorGPS != null ?
                new ObjectParameter("proveedorGPS", proveedorGPS) :
                new ObjectParameter("proveedorGPS", typeof(string));
    
            var nroViajeParameter = nroViaje.HasValue ?
                new ObjectParameter("nroViaje", nroViaje) :
                new ObjectParameter("nroViaje", typeof(int));
    
            var tipoEtisParameter = tipoEtis != null ?
                new ObjectParameter("tipoEtis", tipoEtis) :
                new ObjectParameter("tipoEtis", typeof(string));
    
            var rutClienteParameter = rutCliente != null ?
                new ObjectParameter("rutCliente", rutCliente) :
                new ObjectParameter("rutCliente", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Track_GetMonitoreoOnline_Result>("Track_GetMonitoreoOnline", patenteParameter, transportistaParameter, ignicionParameter, estadoTripParameter, estadoGPSParameter, proveedorGPSParameter, nroViajeParameter, tipoEtisParameter, rutClienteParameter);
        }
    
        public virtual ObjectResult<Track_GetClientes_Result> Track_GetClientes()
        {
            ((IObjectContextAdapter)this).ObjectContext.MetadataWorkspace.LoadFromAssembly(typeof(Track_GetClientes_Result).Assembly);
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Track_GetClientes_Result>("Track_GetClientes");
        }
    
        public virtual ObjectResult<Track_GetDate_Result> Track_GetDate()
        {
            ((IObjectContextAdapter)this).ObjectContext.MetadataWorkspace.LoadFromAssembly(typeof(Track_GetDate_Result).Assembly);
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Track_GetDate_Result>("Track_GetDate");
        }
    
        public virtual ObjectResult<Track_GetZonesInsideZone_Result> Track_GetZonesInsideZone(Nullable<int> idZona)
        {
            ((IObjectContextAdapter)this).ObjectContext.MetadataWorkspace.LoadFromAssembly(typeof(Track_GetZonesInsideZone_Result).Assembly);
    
            var idZonaParameter = idZona.HasValue ?
                new ObjectParameter("idZona", idZona) :
                new ObjectParameter("idZona", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Track_GetZonesInsideZone_Result>("Track_GetZonesInsideZone", idZonaParameter);
        }
    
        public virtual ObjectResult<Track_GetClientesAsociados_Result> Track_GetClientesAsociados(Nullable<int> idZona, string codigoCliente, string nombreCliente)
        {
            ((IObjectContextAdapter)this).ObjectContext.MetadataWorkspace.LoadFromAssembly(typeof(Track_GetClientesAsociados_Result).Assembly);
    
            var idZonaParameter = idZona.HasValue ?
                new ObjectParameter("idZona", idZona) :
                new ObjectParameter("idZona", typeof(int));
    
            var codigoClienteParameter = codigoCliente != null ?
                new ObjectParameter("codigoCliente", codigoCliente) :
                new ObjectParameter("codigoCliente", typeof(string));
    
            var nombreClienteParameter = nombreCliente != null ?
                new ObjectParameter("nombreCliente", nombreCliente) :
                new ObjectParameter("nombreCliente", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Track_GetClientesAsociados_Result>("Track_GetClientesAsociados", idZonaParameter, codigoClienteParameter, nombreClienteParameter);
        }
    
        public virtual ObjectResult<Track_EliminarCliente_Result> Track_EliminarCliente(string codCliente, Nullable<int> codTipoCliente)
        {
            ((IObjectContextAdapter)this).ObjectContext.MetadataWorkspace.LoadFromAssembly(typeof(Track_EliminarCliente_Result).Assembly);
    
            var codClienteParameter = codCliente != null ?
                new ObjectParameter("codCliente", codCliente) :
                new ObjectParameter("codCliente", typeof(string));
    
            var codTipoClienteParameter = codTipoCliente.HasValue ?
                new ObjectParameter("codTipoCliente", codTipoCliente) :
                new ObjectParameter("codTipoCliente", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Track_EliminarCliente_Result>("Track_EliminarCliente", codClienteParameter, codTipoClienteParameter);
        }
    
        public virtual ObjectResult<Track_GetPuntoSafeRoute_Result> Track_GetPuntoSafeRoute(Nullable<int> idSafeRoute)
        {
            ((IObjectContextAdapter)this).ObjectContext.MetadataWorkspace.LoadFromAssembly(typeof(Track_GetPuntoSafeRoute_Result).Assembly);
    
            var idSafeRouteParameter = idSafeRoute.HasValue ?
                new ObjectParameter("IdSafeRoute", idSafeRoute) :
                new ObjectParameter("IdSafeRoute", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Track_GetPuntoSafeRoute_Result>("Track_GetPuntoSafeRoute", idSafeRouteParameter);
        }
    
        public virtual ObjectResult<Track_GetZonasToDrawFromCenter_Result> Track_GetZonasToDrawFromCenter(string latitud, string longitud)
        {
            ((IObjectContextAdapter)this).ObjectContext.MetadataWorkspace.LoadFromAssembly(typeof(Track_GetZonasToDrawFromCenter_Result).Assembly);
    
            var latitudParameter = latitud != null ?
                new ObjectParameter("latitud", latitud) :
                new ObjectParameter("latitud", typeof(string));
    
            var longitudParameter = longitud != null ?
                new ObjectParameter("longitud", longitud) :
                new ObjectParameter("longitud", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Track_GetZonasToDrawFromCenter_Result>("Track_GetZonasToDrawFromCenter", latitudParameter, longitudParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> Track_ExisteZonaEnPunto(string latitud, string longitud, Nullable<int> tipoZona)
        {
            var latitudParameter = latitud != null ?
                new ObjectParameter("latitud", latitud) :
                new ObjectParameter("latitud", typeof(string));
    
            var longitudParameter = longitud != null ?
                new ObjectParameter("longitud", longitud) :
                new ObjectParameter("longitud", typeof(string));
    
            var tipoZonaParameter = tipoZona.HasValue ?
                new ObjectParameter("TipoZona", tipoZona) :
                new ObjectParameter("TipoZona", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("Track_ExisteZonaEnPunto", latitudParameter, longitudParameter, tipoZonaParameter);
        }
    
        public virtual ObjectResult<Track_GetZonasClientesAsociados_Result> Track_GetZonasClientesAsociados(string listCodClientes)
        {
            ((IObjectContextAdapter)this).ObjectContext.MetadataWorkspace.LoadFromAssembly(typeof(Track_GetZonasClientesAsociados_Result).Assembly);
    
            var listCodClientesParameter = listCodClientes != null ?
                new ObjectParameter("listCodClientes", listCodClientes) :
                new ObjectParameter("listCodClientes", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Track_GetZonasClientesAsociados_Result>("Track_GetZonasClientesAsociados", listCodClientesParameter);
        }
    
        public virtual ObjectResult<Track_GetViajesMineria_Result> Track_GetViajesMineria(string nroTransporte, string userName)
        {
            ((IObjectContextAdapter)this).ObjectContext.MetadataWorkspace.LoadFromAssembly(typeof(Track_GetViajesMineria_Result).Assembly);
    
            var nroTransporteParameter = nroTransporte != null ?
                new ObjectParameter("nroTransporte", nroTransporte) :
                new ObjectParameter("nroTransporte", typeof(string));
    
            var userNameParameter = userName != null ?
                new ObjectParameter("userName", userName) :
                new ObjectParameter("userName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Track_GetViajesMineria_Result>("Track_GetViajesMineria", nroTransporteParameter, userNameParameter);
        }
    
        public virtual ObjectResult<Track_GetEstadoPod_Result> Track_GetEstadoPod(string rut)
        {
            ((IObjectContextAdapter)this).ObjectContext.MetadataWorkspace.LoadFromAssembly(typeof(Track_GetEstadoPod_Result).Assembly);
    
            var rutParameter = rut != null ?
                new ObjectParameter("rut", rut) :
                new ObjectParameter("rut", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Track_GetEstadoPod_Result>("Track_GetEstadoPod", rutParameter);
        }
    
        public virtual ObjectResult<Track_GetEstadoPodDetalle_Result> Track_GetEstadoPodDetalle(string rut)
        {
            ((IObjectContextAdapter)this).ObjectContext.MetadataWorkspace.LoadFromAssembly(typeof(Track_GetEstadoPodDetalle_Result).Assembly);
    
            var rutParameter = rut != null ?
                new ObjectParameter("rut", rut) :
                new ObjectParameter("rut", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Track_GetEstadoPodDetalle_Result>("Track_GetEstadoPodDetalle", rutParameter);
        }
    
        //public virtual int Track_UserAltoTrack(string userName)
        //{
        //    var userNameParameter = userName != null ?
        //        new ObjectParameter("UserName", userName) :
        //        new ObjectParameter("UserName", typeof(string));
    
        //    return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Track_UserAltoTrack", userNameParameter);
        //}
    
        //public virtual int Track_GuardarLog(Nullable<int> idUsuario, string ipAddress, string action)
        //{
        //    var idUsuarioParameter = idUsuario.HasValue ?
        //        new ObjectParameter("idUsuario", idUsuario) :
        //        new ObjectParameter("idUsuario", typeof(int));
    
        //    var ipAddressParameter = ipAddress != null ?
        //        new ObjectParameter("ipAddress", ipAddress) :
        //        new ObjectParameter("ipAddress", typeof(string));
    
        //    var actionParameter = action != null ?
        //        new ObjectParameter("action", action) :
        //        new ObjectParameter("action", typeof(string));

        //    //return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Track_GuardarLog", idUsuarioParameter, ipAddressParameter, actionParameter);
        //    return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spu_GpsTrack_GuardarLog", idUsuarioParameter, ipAddressParameter, actionParameter);
        //}
    
        public virtual ObjectResult<Track_GetMonitoreoOnline_Fragil_Result> Track_GetMonitoreoOnline_Fragil(string patente, string transportista, Nullable<int> ignicion, string estadoTrip, string estadoGPS, string proveedorGPS, Nullable<int> nroViaje, string tipoEtis, string viajeFragil, string rutCliente)
        {
            ((IObjectContextAdapter)this).ObjectContext.MetadataWorkspace.LoadFromAssembly(typeof(Track_GetMonitoreoOnline_Fragil_Result).Assembly);
    
            var patenteParameter = patente != null ?
                new ObjectParameter("Patente", patente) :
                new ObjectParameter("Patente", typeof(string));
    
            var transportistaParameter = transportista != null ?
                new ObjectParameter("Transportista", transportista) :
                new ObjectParameter("Transportista", typeof(string));
    
            var ignicionParameter = ignicion.HasValue ?
                new ObjectParameter("Ignicion", ignicion) :
                new ObjectParameter("Ignicion", typeof(int));
    
            var estadoTripParameter = estadoTrip != null ?
                new ObjectParameter("estadoTrip", estadoTrip) :
                new ObjectParameter("estadoTrip", typeof(string));
    
            var estadoGPSParameter = estadoGPS != null ?
                new ObjectParameter("estadoGPS", estadoGPS) :
                new ObjectParameter("estadoGPS", typeof(string));
    
            var proveedorGPSParameter = proveedorGPS != null ?
                new ObjectParameter("proveedorGPS", proveedorGPS) :
                new ObjectParameter("proveedorGPS", typeof(string));
    
            var nroViajeParameter = nroViaje.HasValue ?
                new ObjectParameter("nroViaje", nroViaje) :
                new ObjectParameter("nroViaje", typeof(int));
    
            var tipoEtisParameter = tipoEtis != null ?
                new ObjectParameter("tipoEtis", tipoEtis) :
                new ObjectParameter("tipoEtis", typeof(string));
    
            var viajeFragilParameter = viajeFragil != null ?
                new ObjectParameter("viajeFragil", viajeFragil) :
                new ObjectParameter("viajeFragil", typeof(string));
    
            var rutClienteParameter = rutCliente != null ?
                new ObjectParameter("rutCliente", rutCliente) :
                new ObjectParameter("rutCliente", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Track_GetMonitoreoOnline_Fragil_Result>("Track_GetMonitoreoOnline_Fragil", patenteParameter, transportistaParameter, ignicionParameter, estadoTripParameter, estadoGPSParameter, proveedorGPSParameter, nroViajeParameter, tipoEtisParameter, viajeFragilParameter, rutClienteParameter);
        }
    
        //public virtual ObjectResult<Track_GetFlotaOnline_Fragil_Result> Track_GetFlotaOnline_Fragil(string patente, string transportista, Nullable<int> ignicion, string estadoTrip, string estadoGPS, string proveedorGPS, string viajeFragil)
        //{
        //    ((IObjectContextAdapter)this).ObjectContext.MetadataWorkspace.LoadFromAssembly(typeof(Track_GetFlotaOnline_Fragil_Result).Assembly);
    
        //    var patenteParameter = patente != null ?
        //        new ObjectParameter("Patente", patente) :
        //        new ObjectParameter("Patente", typeof(string));
    
        //    var transportistaParameter = transportista != null ?
        //        new ObjectParameter("Transportista", transportista) :
        //        new ObjectParameter("Transportista", typeof(string));
    
        //    var ignicionParameter = ignicion.HasValue ?
        //        new ObjectParameter("Ignicion", ignicion) :
        //        new ObjectParameter("Ignicion", typeof(int));
    
        //    var estadoTripParameter = estadoTrip != null ?
        //        new ObjectParameter("estadoTrip", estadoTrip) :
        //        new ObjectParameter("estadoTrip", typeof(string));
    
        //    var estadoGPSParameter = estadoGPS != null ?
        //        new ObjectParameter("estadoGPS", estadoGPS) :
        //        new ObjectParameter("estadoGPS", typeof(string));
    
        //    var proveedorGPSParameter = proveedorGPS != null ?
        //        new ObjectParameter("proveedorGPS", proveedorGPS) :
        //        new ObjectParameter("proveedorGPS", typeof(string));
    
        //    var viajeFragilParameter = viajeFragil != null ?
        //        new ObjectParameter("viajeFragil", viajeFragil) :
        //        new ObjectParameter("viajeFragil", typeof(string));
    
        //    return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Track_GetFlotaOnline_Fragil_Result>("Track_GetFlotaOnline_Fragil", patenteParameter, transportistaParameter, ignicionParameter, estadoTripParameter, estadoGPSParameter, proveedorGPSParameter, viajeFragilParameter);
        //}
    
        public virtual ObjectResult<Track_GetViajesControlPanel_Alerce_Result> Track_GetViajesControlPanel_Alerce(Nullable<System.DateTime> desde, Nullable<System.DateTime> hasta, Nullable<int> nroTransporte, Nullable<int> nroOS, string nroContenedor, Nullable<int> idOrigen, Nullable<int> idDestino, string patente, string estadoViaje, string alertas, string userName, string tipoEtis, string cliente)
        {
            ((IObjectContextAdapter)this).ObjectContext.MetadataWorkspace.LoadFromAssembly(typeof(Track_GetViajesControlPanel_Alerce_Result).Assembly);
    
            var desdeParameter = desde.HasValue ?
                new ObjectParameter("desde", desde) :
                new ObjectParameter("desde", typeof(System.DateTime));
    
            var hastaParameter = hasta.HasValue ?
                new ObjectParameter("hasta", hasta) :
                new ObjectParameter("hasta", typeof(System.DateTime));
    
            var nroTransporteParameter = nroTransporte.HasValue ?
                new ObjectParameter("nroTransporte", nroTransporte) :
                new ObjectParameter("nroTransporte", typeof(int));
    
            var nroOSParameter = nroOS.HasValue ?
                new ObjectParameter("nroOS", nroOS) :
                new ObjectParameter("nroOS", typeof(int));
    
            var nroContenedorParameter = nroContenedor != null ?
                new ObjectParameter("nroContenedor", nroContenedor) :
                new ObjectParameter("nroContenedor", typeof(string));
    
            var idOrigenParameter = idOrigen.HasValue ?
                new ObjectParameter("idOrigen", idOrigen) :
                new ObjectParameter("idOrigen", typeof(int));
    
            var idDestinoParameter = idDestino.HasValue ?
                new ObjectParameter("idDestino", idDestino) :
                new ObjectParameter("idDestino", typeof(int));
    
            var patenteParameter = patente != null ?
                new ObjectParameter("patente", patente) :
                new ObjectParameter("patente", typeof(string));
    
            var estadoViajeParameter = estadoViaje != null ?
                new ObjectParameter("estadoViaje", estadoViaje) :
                new ObjectParameter("estadoViaje", typeof(string));
    
            var alertasParameter = alertas != null ?
                new ObjectParameter("alertas", alertas) :
                new ObjectParameter("alertas", typeof(string));
    
            var userNameParameter = userName != null ?
                new ObjectParameter("userName", userName) :
                new ObjectParameter("userName", typeof(string));
    
            var tipoEtisParameter = tipoEtis != null ?
                new ObjectParameter("tipoEtis", tipoEtis) :
                new ObjectParameter("tipoEtis", typeof(string));
    
            var clienteParameter = cliente != null ?
                new ObjectParameter("cliente", cliente) :
                new ObjectParameter("cliente", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Track_GetViajesControlPanel_Alerce_Result>("Track_GetViajesControlPanel_Alerce", desdeParameter, hastaParameter, nroTransporteParameter, nroOSParameter, nroContenedorParameter, idOrigenParameter, idDestinoParameter, patenteParameter, estadoViajeParameter, alertasParameter, userNameParameter, tipoEtisParameter, clienteParameter);
        }
    
        public virtual ObjectResult<Track_GetViajesHistoricos_Alerce_Result> Track_GetViajesHistoricos_Alerce(Nullable<System.DateTime> desde, Nullable<System.DateTime> hasta, Nullable<int> nroTransporte, Nullable<int> nroOS, string nroContenedor, string patente, string estadoViaje, string userName, string tipoEtis, string nombreConductor)
        {
            ((IObjectContextAdapter)this).ObjectContext.MetadataWorkspace.LoadFromAssembly(typeof(Track_GetViajesHistoricos_Alerce_Result).Assembly);
    
            var desdeParameter = desde.HasValue ?
                new ObjectParameter("desde", desde) :
                new ObjectParameter("desde", typeof(System.DateTime));
    
            var hastaParameter = hasta.HasValue ?
                new ObjectParameter("hasta", hasta) :
                new ObjectParameter("hasta", typeof(System.DateTime));
    
            var nroTransporteParameter = nroTransporte.HasValue ?
                new ObjectParameter("nroTransporte", nroTransporte) :
                new ObjectParameter("nroTransporte", typeof(int));
    
            var nroOSParameter = nroOS.HasValue ?
                new ObjectParameter("nroOS", nroOS) :
                new ObjectParameter("nroOS", typeof(int));
    
            var nroContenedorParameter = nroContenedor != null ?
                new ObjectParameter("nroContenedor", nroContenedor) :
                new ObjectParameter("nroContenedor", typeof(string));
    
            var patenteParameter = patente != null ?
                new ObjectParameter("patente", patente) :
                new ObjectParameter("patente", typeof(string));
    
            var estadoViajeParameter = estadoViaje != null ?
                new ObjectParameter("estadoViaje", estadoViaje) :
                new ObjectParameter("estadoViaje", typeof(string));
    
            var userNameParameter = userName != null ?
                new ObjectParameter("userName", userName) :
                new ObjectParameter("userName", typeof(string));
    
            var tipoEtisParameter = tipoEtis != null ?
                new ObjectParameter("tipoEtis", tipoEtis) :
                new ObjectParameter("tipoEtis", typeof(string));
    
            var nombreConductorParameter = nombreConductor != null ?
                new ObjectParameter("nombreConductor", nombreConductor) :
                new ObjectParameter("nombreConductor", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Track_GetViajesHistoricos_Alerce_Result>("Track_GetViajesHistoricos_Alerce", desdeParameter, hastaParameter, nroTransporteParameter, nroOSParameter, nroContenedorParameter, patenteParameter, estadoViajeParameter, userNameParameter, tipoEtisParameter, nombreConductorParameter);
        }
    
        public virtual ObjectResult<Track_GetViajesHistoricos_Alerce_2_Result> Track_GetViajesHistoricos_Alerce_2(Nullable<System.DateTime> desde, Nullable<System.DateTime> hasta, Nullable<int> nroTransporte, string nroContenedor, string patente, string estadoViaje, string userName, string tipoEtis, string nombreConductor)
        {
            ((IObjectContextAdapter)this).ObjectContext.MetadataWorkspace.LoadFromAssembly(typeof(Track_GetViajesHistoricos_Alerce_2_Result).Assembly);
    
            var desdeParameter = desde.HasValue ?
                new ObjectParameter("desde", desde) :
                new ObjectParameter("desde", typeof(System.DateTime));
    
            var hastaParameter = hasta.HasValue ?
                new ObjectParameter("hasta", hasta) :
                new ObjectParameter("hasta", typeof(System.DateTime));
    
            var nroTransporteParameter = nroTransporte.HasValue ?
                new ObjectParameter("nroTransporte", nroTransporte) :
                new ObjectParameter("nroTransporte", typeof(int));
    
            var nroContenedorParameter = nroContenedor != null ?
                new ObjectParameter("nroContenedor", nroContenedor) :
                new ObjectParameter("nroContenedor", typeof(string));
    
            var patenteParameter = patente != null ?
                new ObjectParameter("patente", patente) :
                new ObjectParameter("patente", typeof(string));
    
            var estadoViajeParameter = estadoViaje != null ?
                new ObjectParameter("estadoViaje", estadoViaje) :
                new ObjectParameter("estadoViaje", typeof(string));
    
            var userNameParameter = userName != null ?
                new ObjectParameter("userName", userName) :
                new ObjectParameter("userName", typeof(string));
    
            var tipoEtisParameter = tipoEtis != null ?
                new ObjectParameter("tipoEtis", tipoEtis) :
                new ObjectParameter("tipoEtis", typeof(string));
    
            var nombreConductorParameter = nombreConductor != null ?
                new ObjectParameter("nombreConductor", nombreConductor) :
                new ObjectParameter("nombreConductor", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Track_GetViajesHistoricos_Alerce_2_Result>("Track_GetViajesHistoricos_Alerce_2", desdeParameter, hastaParameter, nroTransporteParameter, nroContenedorParameter, patenteParameter, estadoViajeParameter, userNameParameter, tipoEtisParameter, nombreConductorParameter);
        }
    
        public virtual ObjectResult<Track_GetViajesControlPanel_Alerce_2_Result> Track_GetViajesControlPanel_Alerce_2(Nullable<System.DateTime> desde, Nullable<System.DateTime> hasta, Nullable<int> nroTransporte, string nroContenedor, Nullable<int> idOrigen, Nullable<int> idDestino, string patente, string estadoViaje, string alertas, string userName, string tipoEtis, string cliente)
        {
            ((IObjectContextAdapter)this).ObjectContext.MetadataWorkspace.LoadFromAssembly(typeof(Track_GetViajesControlPanel_Alerce_2_Result).Assembly);
    
            var desdeParameter = desde.HasValue ?
                new ObjectParameter("desde", desde) :
                new ObjectParameter("desde", typeof(System.DateTime));
    
            var hastaParameter = hasta.HasValue ?
                new ObjectParameter("hasta", hasta) :
                new ObjectParameter("hasta", typeof(System.DateTime));
    
            var nroTransporteParameter = nroTransporte.HasValue ?
                new ObjectParameter("nroTransporte", nroTransporte) :
                new ObjectParameter("nroTransporte", typeof(int));
    
            var nroContenedorParameter = nroContenedor != null ?
                new ObjectParameter("nroContenedor", nroContenedor) :
                new ObjectParameter("nroContenedor", typeof(string));
    
            var idOrigenParameter = idOrigen.HasValue ?
                new ObjectParameter("idOrigen", idOrigen) :
                new ObjectParameter("idOrigen", typeof(int));
    
            var idDestinoParameter = idDestino.HasValue ?
                new ObjectParameter("idDestino", idDestino) :
                new ObjectParameter("idDestino", typeof(int));
    
            var patenteParameter = patente != null ?
                new ObjectParameter("patente", patente) :
                new ObjectParameter("patente", typeof(string));
    
            var estadoViajeParameter = estadoViaje != null ?
                new ObjectParameter("estadoViaje", estadoViaje) :
                new ObjectParameter("estadoViaje", typeof(string));
    
            var alertasParameter = alertas != null ?
                new ObjectParameter("alertas", alertas) :
                new ObjectParameter("alertas", typeof(string));
    
            var userNameParameter = userName != null ?
                new ObjectParameter("userName", userName) :
                new ObjectParameter("userName", typeof(string));
    
            var tipoEtisParameter = tipoEtis != null ?
                new ObjectParameter("tipoEtis", tipoEtis) :
                new ObjectParameter("tipoEtis", typeof(string));
    
            var clienteParameter = cliente != null ?
                new ObjectParameter("cliente", cliente) :
                new ObjectParameter("cliente", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Track_GetViajesControlPanel_Alerce_2_Result>("Track_GetViajesControlPanel_Alerce_2", desdeParameter, hastaParameter, nroTransporteParameter, nroContenedorParameter, idOrigenParameter, idDestinoParameter, patenteParameter, estadoViajeParameter, alertasParameter, userNameParameter, tipoEtisParameter, clienteParameter);
        }
    
        public virtual ObjectResult<Track_GetClientesUsuario_Result> Track_GetClientesUsuario(string userName)
        {
            ((IObjectContextAdapter)this).ObjectContext.MetadataWorkspace.LoadFromAssembly(typeof(Track_GetClientesUsuario_Result).Assembly);
    
            var userNameParameter = userName != null ?
                new ObjectParameter("userName", userName) :
                new ObjectParameter("userName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Track_GetClientesUsuario_Result>("Track_GetClientesUsuario", userNameParameter);
        }
    }
}
