//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UtilitiesLayer.ServiceTrack_GoogleAPI {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceTrack_GoogleAPI.ITrack_GoogleAPI")]
    public interface ITrack_GoogleAPI {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITrack_GoogleAPI/GetGoogleETA", ReplyAction="http://tempuri.org/ITrack_GoogleAPI/GetGoogleETAResponse")]
        string GetGoogleETA(string pObject);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITrack_GoogleAPIChannel : UtilitiesLayer.ServiceTrack_GoogleAPI.ITrack_GoogleAPI, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Track_GoogleAPIClient : System.ServiceModel.ClientBase<UtilitiesLayer.ServiceTrack_GoogleAPI.ITrack_GoogleAPI>, UtilitiesLayer.ServiceTrack_GoogleAPI.ITrack_GoogleAPI {
        
        public Track_GoogleAPIClient() {
        }
        
        public Track_GoogleAPIClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Track_GoogleAPIClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Track_GoogleAPIClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Track_GoogleAPIClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetGoogleETA(string pObject) {
            return base.Channel.GetGoogleETA(pObject);
        }
    }
}
